version: '3.13'

services:
  neo4j:
    image: neo4j:4.4
    container_name: neo4j_db
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  flask_app:
    build: .
    container_name: flask_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=infestation
    volumes:
      - flask_data:/app/data

volumes:
  neo4j_data:
  flask_data:
